// flow-typed signature: fe4650ee1af97004dfc51699d9e2bdf2
// flow-typed version: <<STUB>>/@storybook/addon-info_v^3.3.14/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-info'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-info' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-info/dist/components/makeTableComponent' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/markdown/code' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/markdown/htags' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/markdown/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/markdown/text' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/Node' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/Props' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/PropTable' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/PropVal' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/Story' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/types/ArrayOf' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/types/Enum' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/types/InstanceOf' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/types/Literal' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/types/Object' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/types/ObjectOf' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/types/ObjectType' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/types/OneOf' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/types/OneOfType' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/types/PrettyPropType' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/types/PropertyLabel' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/types/proptypes' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/types/Shape' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/types/Signature' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/example/Button' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/example/story' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/src/components/makeTableComponent' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/src/components/markdown/code' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/src/components/markdown/htags' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/src/components/markdown/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/src/components/markdown/text' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/src/components/Node' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/src/components/Props' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/src/components/PropTable' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/src/components/PropTable.test' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/src/components/PropVal' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/src/components/Story' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/src/components/types/ArrayOf' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/src/components/types/Enum' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/src/components/types/InstanceOf' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/src/components/types/Literal' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/src/components/types/Object' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/src/components/types/ObjectOf' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/src/components/types/ObjectType' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/src/components/types/OneOf' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/src/components/types/OneOfType' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/src/components/types/PrettyPropType' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/src/components/types/PropertyLabel' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/src/components/types/proptypes' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/src/components/types/Shape' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/src/components/types/Signature' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/src/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/src/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-info/dist/components/makeTableComponent.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/makeTableComponent'>;
}
declare module '@storybook/addon-info/dist/components/markdown/code.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/markdown/code'>;
}
declare module '@storybook/addon-info/dist/components/markdown/htags.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/markdown/htags'>;
}
declare module '@storybook/addon-info/dist/components/markdown/index.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/markdown/index'>;
}
declare module '@storybook/addon-info/dist/components/markdown/text.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/markdown/text'>;
}
declare module '@storybook/addon-info/dist/components/Node.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/Node'>;
}
declare module '@storybook/addon-info/dist/components/Props.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/Props'>;
}
declare module '@storybook/addon-info/dist/components/PropTable.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/PropTable'>;
}
declare module '@storybook/addon-info/dist/components/PropVal.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/PropVal'>;
}
declare module '@storybook/addon-info/dist/components/Story.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/Story'>;
}
declare module '@storybook/addon-info/dist/components/types/ArrayOf.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/types/ArrayOf'>;
}
declare module '@storybook/addon-info/dist/components/types/Enum.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/types/Enum'>;
}
declare module '@storybook/addon-info/dist/components/types/InstanceOf.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/types/InstanceOf'>;
}
declare module '@storybook/addon-info/dist/components/types/Literal.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/types/Literal'>;
}
declare module '@storybook/addon-info/dist/components/types/Object.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/types/Object'>;
}
declare module '@storybook/addon-info/dist/components/types/ObjectOf.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/types/ObjectOf'>;
}
declare module '@storybook/addon-info/dist/components/types/ObjectType.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/types/ObjectType'>;
}
declare module '@storybook/addon-info/dist/components/types/OneOf.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/types/OneOf'>;
}
declare module '@storybook/addon-info/dist/components/types/OneOfType.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/types/OneOfType'>;
}
declare module '@storybook/addon-info/dist/components/types/PrettyPropType.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/types/PrettyPropType'>;
}
declare module '@storybook/addon-info/dist/components/types/PropertyLabel.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/types/PropertyLabel'>;
}
declare module '@storybook/addon-info/dist/components/types/proptypes.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/types/proptypes'>;
}
declare module '@storybook/addon-info/dist/components/types/Shape.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/types/Shape'>;
}
declare module '@storybook/addon-info/dist/components/types/Signature.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/types/Signature'>;
}
declare module '@storybook/addon-info/dist/index.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/index'>;
}
declare module '@storybook/addon-info/example/Button.js' {
  declare module.exports: $Exports<'@storybook/addon-info/example/Button'>;
}
declare module '@storybook/addon-info/example/story.js' {
  declare module.exports: $Exports<'@storybook/addon-info/example/story'>;
}
declare module '@storybook/addon-info/src/components/makeTableComponent.js' {
  declare module.exports: $Exports<'@storybook/addon-info/src/components/makeTableComponent'>;
}
declare module '@storybook/addon-info/src/components/markdown/code.js' {
  declare module.exports: $Exports<'@storybook/addon-info/src/components/markdown/code'>;
}
declare module '@storybook/addon-info/src/components/markdown/htags.js' {
  declare module.exports: $Exports<'@storybook/addon-info/src/components/markdown/htags'>;
}
declare module '@storybook/addon-info/src/components/markdown/index.js' {
  declare module.exports: $Exports<'@storybook/addon-info/src/components/markdown/index'>;
}
declare module '@storybook/addon-info/src/components/markdown/text.js' {
  declare module.exports: $Exports<'@storybook/addon-info/src/components/markdown/text'>;
}
declare module '@storybook/addon-info/src/components/Node.js' {
  declare module.exports: $Exports<'@storybook/addon-info/src/components/Node'>;
}
declare module '@storybook/addon-info/src/components/Props.js' {
  declare module.exports: $Exports<'@storybook/addon-info/src/components/Props'>;
}
declare module '@storybook/addon-info/src/components/PropTable.js' {
  declare module.exports: $Exports<'@storybook/addon-info/src/components/PropTable'>;
}
declare module '@storybook/addon-info/src/components/PropTable.test.js' {
  declare module.exports: $Exports<'@storybook/addon-info/src/components/PropTable.test'>;
}
declare module '@storybook/addon-info/src/components/PropVal.js' {
  declare module.exports: $Exports<'@storybook/addon-info/src/components/PropVal'>;
}
declare module '@storybook/addon-info/src/components/Story.js' {
  declare module.exports: $Exports<'@storybook/addon-info/src/components/Story'>;
}
declare module '@storybook/addon-info/src/components/types/ArrayOf.js' {
  declare module.exports: $Exports<'@storybook/addon-info/src/components/types/ArrayOf'>;
}
declare module '@storybook/addon-info/src/components/types/Enum.js' {
  declare module.exports: $Exports<'@storybook/addon-info/src/components/types/Enum'>;
}
declare module '@storybook/addon-info/src/components/types/InstanceOf.js' {
  declare module.exports: $Exports<'@storybook/addon-info/src/components/types/InstanceOf'>;
}
declare module '@storybook/addon-info/src/components/types/Literal.js' {
  declare module.exports: $Exports<'@storybook/addon-info/src/components/types/Literal'>;
}
declare module '@storybook/addon-info/src/components/types/Object.js' {
  declare module.exports: $Exports<'@storybook/addon-info/src/components/types/Object'>;
}
declare module '@storybook/addon-info/src/components/types/ObjectOf.js' {
  declare module.exports: $Exports<'@storybook/addon-info/src/components/types/ObjectOf'>;
}
declare module '@storybook/addon-info/src/components/types/ObjectType.js' {
  declare module.exports: $Exports<'@storybook/addon-info/src/components/types/ObjectType'>;
}
declare module '@storybook/addon-info/src/components/types/OneOf.js' {
  declare module.exports: $Exports<'@storybook/addon-info/src/components/types/OneOf'>;
}
declare module '@storybook/addon-info/src/components/types/OneOfType.js' {
  declare module.exports: $Exports<'@storybook/addon-info/src/components/types/OneOfType'>;
}
declare module '@storybook/addon-info/src/components/types/PrettyPropType.js' {
  declare module.exports: $Exports<'@storybook/addon-info/src/components/types/PrettyPropType'>;
}
declare module '@storybook/addon-info/src/components/types/PropertyLabel.js' {
  declare module.exports: $Exports<'@storybook/addon-info/src/components/types/PropertyLabel'>;
}
declare module '@storybook/addon-info/src/components/types/proptypes.js' {
  declare module.exports: $Exports<'@storybook/addon-info/src/components/types/proptypes'>;
}
declare module '@storybook/addon-info/src/components/types/Shape.js' {
  declare module.exports: $Exports<'@storybook/addon-info/src/components/types/Shape'>;
}
declare module '@storybook/addon-info/src/components/types/Signature.js' {
  declare module.exports: $Exports<'@storybook/addon-info/src/components/types/Signature'>;
}
declare module '@storybook/addon-info/src/index.js' {
  declare module.exports: $Exports<'@storybook/addon-info/src/index'>;
}
declare module '@storybook/addon-info/src/index.test.js' {
  declare module.exports: $Exports<'@storybook/addon-info/src/index.test'>;
}
